name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The app version to be release"
        required: true
jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate version code
        id: generate-version-code
        run: |
          echo "VERSION_CODE=$((${{ github.run_number }} + 20))" >> "$GITHUB_OUTPUT"
      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ steps.generate-version-code.outputs.VERSION_CODE }}
          versionName: ${{ github.event.inputs.version }}
      - name: Open pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "bump: ${{ github.event.inputs.version }}"
          title: "bump: ${{ github.event.inputs.version }}"
          body: "Bump versionName of the app"
          branch: bump/${{ github.event.inputs.version }}
          base: main
          add-paths: |
            *.gradle.kts
