name: SnapshotTest

on:
  workflow_dispatch:
  pull_request:
    branches-ignore:
      - 'bump/**'
    paths-ignore:
      - 'README.md'
      - 'image/**'

jobs:
  snapshot-testing-and-report:

    permissions:
      pull-requests: write
      issues: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run screenshot tests
        id: verifyRoborazziDebug
        continue-on-error: true
        run: ./gradlew verifyRoborazziDebug -Psnapshot

      - name: Upload Test Diff
        uses: actions/upload-artifact@v3.1.2
        if: ${{ always() }}
        with:
          name: snapshot-test-diff
          path: |
            **/build/outputs/roborazzi
          retention-days: 30

      - name: Upload Test Result
        uses: actions/upload-artifact@v3.1.2
        if: ${{ always() }}
        with:
          name: snapshot-test-results
          path: |
            **/build/test-results
          retention-days: 30

      - name: Check _compare files
        id: check-compare-files
        shell: bash
        run: |
          # Find all the files ending with _compare.png
          mapfile -t files_to_add < <(find . -type f -name "*_compare.png")
          
          # Check for invalid file names and add only valid ones
          exist_valid_files="false"
          for file in "${files_to_add[@]}"; do
            if [[ $file =~ ^[a-zA-Z0-9_./-]+$ ]]; then
              exist_valid_files="true"
              break
            fi
          done
          echo "exist_valid_files=$exist_valid_files" >> "$GITHUB_OUTPUT"

      - name: Generate diff reports
        id: generate-diff-reports
        if: steps.check-compare-files.outputs.exist_valid_files == 'true'
        env:
          BRANCH_NAME: ${{ github.event.workflow_run.head_branch }}
        shell: bash
        run: |
          # Find all the files ending with _compare.png in roborazzi folder
          files=$(find . -type f -name "*_compare.png" | grep "roborazzi/" | grep -E "^[a-zA-Z0-9_./-]+$")
          delimiter="$(openssl rand -hex 8)"
          {
            echo "reports<<${delimiter}"
          
            # Create markdown table header
            echo "### Snapshot Testing Diff Report"
            echo "| File name | Image |"
            echo "|-------|-------|"
          } >> "$GITHUB_OUTPUT"
          
          # Iterate over the files and create table rows
          for file in $files; do
            # Get the file name and insert newlines every 20 characters
            fileName=$(basename "$file" | sed -r 's/(.{20})/\1<br>/g')
            urlPart="${BRANCH_NAME//#/%23}/${file//#/%23}"
            echo "| [$fileName](https://github.com/${{ github.repository }}/blob/$urlPart) | ![](https://github.com/${{ github.repository }}/blob/$urlPart?raw=true) |" >> "$GITHUB_OUTPUT"
          done
          echo "${delimiter}" >> "$GITHUB_OUTPUT"

      - name: Find comment
        uses: peter-evans/find-comment@v3
        id: find-comment
        if: steps.generate-diff-reports.outputs.reports != ''
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Snapshot Testing Diff Report

      - name: Add or update comment on PR
        uses: peter-evans/create-or-update-comment@v4
        if: steps.generate-diff-reports.outputs.reports != ''
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.number }}
          body: ${{ steps.generate-diff-reports.outputs.reports }}
          edit-mode: replace
