name: Update the Gradle Wrapper

on:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

permissions: read-all

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update the Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
